name: Create release on develop tag

on:
  push:
    branches:
      - "develop"
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+"
      

permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.ITFIT_QP_TOKEN }}
