# This workflow will upload a Python Package using Twine when push to develop to testPyPi

name: Upload Python Package to testPyPi

on:
  push:
    branches: 
    - develop

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install bumpver
    - name: Update patch version
      run: |
        bumpver update --patch --dry
        bumpver update --patch
    - name: Commit and push
      run: |
<<<<<<< HEAD
=======
        git config --global
>>>>>>> d772f052f1622780e3743fec5503dc1e558455ec
        git commit -amend --no-edit
        git push

    - name: Build package
      run: python -m build
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
